// AUTO-GENERATED by tools/fetch-pexels.mjs — DO NOT EDIT BY HAND

export type ImageData = {
  src: string;
  alt: string;
  photographer: string;
  photographerUrl: string;
  pexelsUrl: string;
};

export const PRODUCER_IMAGES: Record<string, ImageData> = {
  "jean-bertaud": {
    "src": "/images/producteurs/jean-bertaud.jpg",
    "alt": "Vibrant assortment of green olives in a processing crate, ready for sorting.",
    "photographer": "Chermiti Mohamed",
    "photographerUrl": "https://www.pexels.com/@chermitove",
    "pexelsUrl": "https://www.pexels.com/photo/close-up-of-freshly-harvested-green-olives-29878981/"
  },
  "maryse-ferrand": {
    "src": "/images/producteurs/maryse-ferrand.jpg",
    "alt": "A smiling woman feeds a goat outdoors, capturing a peaceful countryside moment.",
    "photographer": "Anastasia  Shuraeva",
    "photographerUrl": "https://www.pexels.com/@anastasia-shuraeva",
    "pexelsUrl": "https://www.pexels.com/photo/a-woman-feeding-animals-7671867/"
  },
  "domaine-reibaud": {
    "src": "/images/producteurs/domaine-reibaud.jpg",
    "alt": "Hands filling wine bottles in an outdoor setting in Nouvelle-Aquitaine, France.",
    "photographer": "Alex Grandidier",
    "photographerUrl": "https://www.pexels.com/@alex-grandidier-2159174194",
    "pexelsUrl": "https://www.pexels.com/photo/winemaking-process-in-nouvelle-aquitaine-35855519/"
  },
  "famille-sicard": {
    "src": "/images/producteurs/famille-sicard.jpg",
    "alt": "A beautiful and vibrant lavender field in Provence, perfect for natural landscape lovers.",
    "photographer": "Pixabay",
    "photographerUrl": "https://www.pexels.com/@pixabay",
    "pexelsUrl": "https://www.pexels.com/photo/macro-shot-photography-of-purple-plants-under-sunny-sky-during-daytime-139396/"
  },
  "pascal-roux": {
    "src": "/images/producteurs/pascal-roux.jpg",
    "alt": "Close-up of various meats hanging on hooks in a butcher shop.",
    "photographer": "Noemí Jiménez",
    "photographerUrl": "https://www.pexels.com/@noemiji",
    "pexelsUrl": "https://www.pexels.com/photo/assorted-meats-hanging-in-a-butcher-shop-37663507/"
  },
  "atelier-brun": {
    "src": "/images/producteurs/atelier-brun.jpg",
    "alt": "A collection of artisan sourdough loaves displayed in a rustic bakery setting.",
    "photographer": "Magda Ehlers",
    "photographerUrl": "https://www.pexels.com/@magda-ehlers-pexels",
    "pexelsUrl": "https://www.pexels.com/photo/artisan-sourdough-bread-display-in-bakery-30826792/"
  },
  "jardins-de-regine": {
    "src": "/images/producteurs/jardins-de-regine.jpg",
    "alt": "A person arranging bags of turnips in an outdoor agricultural setting.",
    "photographer": "Emrehan  Çolak",
    "photographerUrl": "https://www.pexels.com/@emrehan-colak-1667477484",
    "pexelsUrl": "https://www.pexels.com/photo/worker-organizing-bagged-turnips-outdoors-36719739/"
  },
  "pierre-calas": {
    "src": "/images/producteurs/pierre-calas.jpg",
    "alt": "Beekeeper wearing protective suit examining honeycomb outdoors.",
    "photographer": "Vitaly Gariev",
    "photographerUrl": "https://www.pexels.com/@silverkblack",
    "pexelsUrl": "https://www.pexels.com/photo/beekeeper-inspecting-honeycomb-in-lush-garden-36813213/"
  }
};
