// AUTO-GENERATED by tools/fetch-pexels.mjs — DO NOT EDIT BY HAND
// Run: node tools/fetch-pexels.mjs

export type ImageData = {
  src: string;
  alt: string;
  photographer: string;
  photographerUrl: string;
  pexelsUrl: string;
};

export const RECIPE_IMAGES: Record<string, ImageData> = {
  "aioli-traditionnel": {
    "src": "/images/recettes/aioli-traditionnel.jpg",
    "alt": "A creamy white sauce elegantly presented with garlic and olives on a slate board.",
    "photographer": "Demian Grygorchuk",
    "photographerUrl": "https://www.pexels.com/@demian-grygorchuk-1976256",
    "pexelsUrl": "https://www.pexels.com/photo/a-flatlay-of-a-white-sauce-in-a-glass-bowl-8053728/"
  },
  "ratatouille-confite": {
    "src": "/images/recettes/ratatouille-confite.jpg",
    "alt": "Close-up of a vibrant, fresh ratatouille with tomatoes, eggplants, and spices.",
    "photographer": "Edita Brus",
    "photographerUrl": "https://www.pexels.com/@edita-brus-2027796741",
    "pexelsUrl": "https://www.pexels.com/photo/colorful-vegan-ratatouille-dish-close-up-36040965/"
  },
  "daube-avignonnaise": {
    "src": "/images/recettes/daube-avignonnaise.jpg",
    "alt": "Overhead view of a sophisticated dining setup with a main course, red wine, and a lit candle, highlighting a special occasion.",
    "photographer": "furkanfdemir",
    "photographerUrl": "https://www.pexels.com/@furkanfdemir",
    "pexelsUrl": "https://www.pexels.com/photo/woman-sitting-at-table-during-dinner-10821365/"
  },
  "tian-legumes-soleil": {
    "src": "/images/recettes/tian-legumes-soleil.jpg",
    "alt": "Delicious baked vegetable casserole topped with cheese in a white dish on a wooden board.",
    "photographer": "Sylwester Ficek",
    "photographerUrl": "https://www.pexels.com/@sylwester-ficek-154797634",
    "pexelsUrl": "https://www.pexels.com/photo/cheesy-vegetable-baked-casserole-in-white-dish-32039641/"
  },
  "tapenade-noire-aups": {
    "src": "/images/recettes/tapenade-noire-aups.jpg",
    "alt": "Close-up of tapenade with a cherry tomato garnish in a rustic ceramic bowl.",
    "photographer": "Anthony Rahayel",
    "photographerUrl": "https://www.pexels.com/@anthony-rahayel-125801377",
    "pexelsUrl": "https://www.pexels.com/photo/rustic-tapenade-in-ceramic-bowl-with-tomato-30325082/"
  },
  "soupe-au-pistou": {
    "src": "/images/recettes/soupe-au-pistou.jpg",
    "alt": "Close-up of a wooden spoon holding fresh vegetables over simmering soup.",
    "photographer": "Jade  Sandra",
    "photographerUrl": "https://www.pexels.com/@jadesandra",
    "pexelsUrl": "https://www.pexels.com/photo/delicious-vegetable-soup-with-fresh-ingredients-36511370/"
  },
  "pissaladiere-nice": {
    "src": "/images/recettes/pissaladiere-nice.jpg",
    "alt": "A delicious and colorful vegetable tart featuring cherry tomatoes, zucchini, and onions.",
    "photographer": "Laura oliveira",
    "photographerUrl": "https://www.pexels.com/@laura-oliveira-2156849568",
    "pexelsUrl": "https://www.pexels.com/photo/fresh-vegetable-tart-with-cherry-tomatoes-and-zucchini-34429582/"
  },
  "fougasse-aux-olives": {
    "src": "/images/recettes/fougasse-aux-olives.jpg",
    "alt": "Close-up of freshly baked Italian focaccia with garlic and rosemary on parchment paper.",
    "photographer": "Lucie Liz",
    "photographerUrl": "https://www.pexels.com/@lulizler",
    "pexelsUrl": "https://www.pexels.com/photo/delicious-focaccia-on-paper-18453903/"
  },
  "brandade-nimoise": {
    "src": "/images/recettes/brandade-nimoise.jpg",
    "alt": "Sliced rye bread with fish and cream cheese garnished with dill on a dark surface.",
    "photographer": "Vilnis Husko",
    "photographerUrl": "https://www.pexels.com/@vhusko",
    "pexelsUrl": "https://www.pexels.com/photo/close-up-of-cake-with-fish-8618431/"
  },
  "panisses-marseille": {
    "src": "/images/recettes/panisses-marseille.jpg",
    "alt": "Top view of crispy vegetable fritters with onions and chickpeas on a wooden table.",
    "photographer": "Rachel Claire",
    "photographerUrl": "https://www.pexels.com/@rachel-claire",
    "pexelsUrl": "https://www.pexels.com/photo/top-view-of-fried-vegetable-cakes-and-onions-on-a-weathered-wood-5863613/"
  },
  "pieds-paquets-marseillais": {
    "src": "/images/recettes/pieds-paquets-marseillais.jpg",
    "alt": "Savory vegetable stew served in cast iron on wooden board, paired with garlic cloves and kitchen utensils.",
    "photographer": "Marcelo Verfe",
    "photographerUrl": "https://www.pexels.com/@marceloverfe",
    "pexelsUrl": "https://www.pexels.com/photo/food-in-pot-on-tray-16699419/"
  },
  "tarte-tropezienne": {
    "src": "/images/recettes/tarte-tropezienne.jpg",
    "alt": "Mouth-watering dessert featuring fresh raspberries and cream on a glazed pastry, perfect for a sweet treat.",
    "photographer": "Anthony Rahayel",
    "photographerUrl": "https://www.pexels.com/@anthony-rahayel-125801377",
    "pexelsUrl": "https://www.pexels.com/photo/delicious-raspberry-dessert-with-cream-topping-32134460/"
  },
  "orecchiette-brocolis": {
    "src": "/images/recettes/orecchiette-brocolis.jpg",
    "alt": "Delicious orecchiette pasta served with meat sauce at a sunlit dining table.",
    "photographer": "Paolo Galuppo",
    "photographerUrl": "https://www.pexels.com/@paolo-galuppo-1673439610",
    "pexelsUrl": "https://www.pexels.com/photo/savoring-orecchiette-pasta-with-meat-sauce-36853437/"
  },
  "paella-valenciana": {
    "src": "/images/recettes/paella-valenciana.jpg",
    "alt": "A vibrant and flavorful seafood paella served in a pan with mussels and shrimp.",
    "photographer": "Marcelo Verfe",
    "photographerUrl": "https://www.pexels.com/@marceloverfe",
    "pexelsUrl": "https://www.pexels.com/photo/seafood-paella-with-lobster-16743486/"
  },
  "tagine-agneau-citron": {
    "src": "/images/recettes/tagine-agneau-citron.jpg",
    "alt": "A savory Moroccan tagine garnished with fresh herbs, served in a traditional dish.",
    "photographer": "Abby Chung",
    "photographerUrl": "https://www.pexels.com/@abby-chung-371167",
    "pexelsUrl": "https://www.pexels.com/photo/food-998244/"
  },
  "hommos-moutabal": {
    "src": "/images/recettes/hommos-moutabal.jpg",
    "alt": "Delicious Middle Eastern mezze platter featuring assorted pita bread, dips like hummus and baba ghanoush.",
    "photographer": "Karolina Grabowska www.kaboompics.com",
    "photographerUrl": "https://www.pexels.com/@karola-g2",
    "pexelsUrl": "https://www.pexels.com/photo/lunch-5944/"
  },
  "pizza-margherita-levain": {
    "src": "/images/recettes/pizza-margherita-levain.jpg",
    "alt": "Close-up of a fresh Margherita pizza with tomatoes and basil. Perfect for Italian cuisine promotions.",
    "photographer": "Sonali Mehta",
    "photographerUrl": "https://www.pexels.com/@sonali-mehta-1514525371",
    "pexelsUrl": "https://www.pexels.com/photo/delicious-margherita-pizza-with-fresh-toppings-31596394/"
  },
  "salade-grecque-traditionnelle": {
    "src": "/images/recettes/salade-grecque-traditionnelle.jpg",
    "alt": "A delicious Greek salad featuring feta cheese, olives, and fresh vegetables in a rustic bowl.",
    "photographer": "Valeria Boltneva",
    "photographerUrl": "https://www.pexels.com/@valeriya",
    "pexelsUrl": "https://www.pexels.com/photo/vegetable-slices-on-brown-ceramic-bowl-724669/"
  },
  "couscous-sept-legumes": {
    "src": "/images/recettes/couscous-sept-legumes.jpg",
    "alt": "Couscous dish creatively plated with basil and cherry tomatoes on a slate plate.",
    "photographer": "Enzo Iorio",
    "photographerUrl": "https://www.pexels.com/@enzo-iorio-381015179",
    "pexelsUrl": "https://www.pexels.com/photo/a-plate-with-a-small-dish-of-food-on-it-27662767/"
  },
  "loup-de-mer-citron": {
    "src": "/images/recettes/loup-de-mer-citron.jpg",
    "alt": "Freshly baked trout in an aluminum tray garnished with lemon, herbs, and spices.",
    "photographer": "Sylwester Ficek",
    "photographerUrl": "https://www.pexels.com/@sylwester-ficek-154797634",
    "pexelsUrl": "https://www.pexels.com/photo/marinade-fish-in-aluminum-container-12653380/"
  },
  "lasagnes-ragu-bolognaise": {
    "src": "/images/recettes/lasagnes-ragu-bolognaise.jpg",
    "alt": "Close-up shot of a cheesy homemade lasagna slice on a plate, highlighting its layers and garnish.",
    "photographer": "素材王国 Footage Kingdom",
    "photographerUrl": "https://www.pexels.com/@footage-kingdom-122917970",
    "pexelsUrl": "https://www.pexels.com/photo/lasagna-on-a-plate-13823542/"
  }
};
