// AUTO-GENERATED by tools/fetch-team-portraits.mjs — DO NOT EDIT BY HAND

export type ImageData = {
  src: string; alt: string; photographer: string;
  photographerUrl: string; pexelsUrl: string;
};

export const TEAM_IMAGES: Record<string, ImageData> = {
  "camille-aubert": {
    "src": "/images/team/camille-aubert.jpg",
    "alt": "Female chef standing confidently in a professional kitchen, showcasing culinary professionalism.",
    "photographer": "Hazel Montero",
    "photographerUrl": "https://www.pexels.com/@zaylard",
    "pexelsUrl": "https://www.pexels.com/photo/a-woman-working-in-a-restaurant-kitchen-16816198/"
  },
  "leo-pinault": {
    "src": "/images/team/leo-pinault.jpg",
    "alt": "Young male barista working in a trendy café setting, wearing an apron.",
    "photographer": "Fatima Said",
    "photographerUrl": "https://www.pexels.com/@fatima-said-725739765",
    "pexelsUrl": "https://www.pexels.com/photo/waiter-in-apron-and-shirt-at-cafe-20609544/"
  },
  "ines-cabrol": {
    "src": "/images/team/ines-cabrol.jpg",
    "alt": "A woman with blonde hair holding a glass of red wine in a cozy setting.",
    "photographer": "Nadin Sh",
    "photographerUrl": "https://www.pexels.com/@nadin-sh-78971847",
    "pexelsUrl": "https://www.pexels.com/photo/blonde-woman-holding-a-glass-of-red-wine-9541977/"
  }
};
